# <a href="https://colab.research.google.com/drive/1dbxo-7ivFXc3vLt3v2v2JDfVZsXzqzEe?usp=sharing">Click Here</a> to open this file in Google Colab

# NUMPY 

So lets have a basic exercise on numpy. 

In [2]:
import numpy as np 

#### create an array of 10 tens 

In [21]:
array=np.ones((10),dtype=int)*10
print("An array of 10 tens:")
array

An array of 10 tens:


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of all the odd integers from 100 to 200

In [22]:
array1=np.arange(101,200,2)
print("Array of all the even integers from 100 to 200 : ")
array1 


Array of all the even integers from 100 to 200 : 


array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
       127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151,
       153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177,
       179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199])

#### Create a 3x3 identity matrix

In [25]:
array2=np.identity((3),dtype=int)
print('3x3 matrix:')
array2


3x3 matrix:


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### write a code that gives the output given below
 ** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **



In [49]:
arr4=np.arange(1,26).reshape((5,5))
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Given :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create a 4X4 matrix with values starting from 0

In [47]:
arr4=np.arange(0,16).reshape((4,4))
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [50]:
rand_num = np.random.normal(0,1,9)
print("9 random numbers from a standard normal distribution:")
rand_num


9 random numbers from a standard normal distribution:


array([-1.21260851,  0.07366652, -0.13135857,  1.11227475,  0.30891979,
       -1.56985339, -1.19677088,  1.45045249, -1.05713144])

In [51]:
j=np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### on the given above array 'j' , perform the given questions. 

#### 1. Get the standard deviation of the values in mat

In [52]:
np.std(j, dtype=np.float64)


3.452052529534663

#### 2. Get the sum of all the columns in mat

In [54]:
print("Sum Of all the columns in mat : ")
j.sum(axis=0)



Sum Of all the columns in mat : 


array([48, 51, 54, 57])

#### 3. write a code that gives the following output given below.
** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **

In [62]:
arr5=np.arange(13,22,4).reshape(3,1)
arr5

array([[13],
       [17],
       [21]])

# Given :

array([[13],
       [17],
       [21]])

#### 4. Get the sum of all the values in mat

In [63]:
print("the sum of all the values in mat : ",np.sum(arr5))


the sum of all the values in mat :  51


# Submitted By : <a href="https://www.linkedin.com/in/saurabh-satapathy-692a6a1b9">Saurabh Satapathy</a> 

# GLAD YOU COMPLETED THIS PART, GOOD LUCK AHEAD!!